# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Sydney University Graduates Union North America"
#subtitle: "SUGUNA"
masthead_title: "SUGUNA"
logo: "/assets/images/suguna-logo-88x88.png"
#email: alumni.suguna@usydnorthamerica.org
description: >- # this means to ignore newlines until nextitem
  SUGUNA website
url: https://usydnorthamerica.org # your custom domain
baseurl: "" # leave this blank for a custom domain
#baseurl: "/suguna-minimalm" 
minimal_mistakes_skin: default
#search: true

minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include: ["_pages"]

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

  
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/sydney-university-graduates-union-north-america/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/SUGUNAalumni"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/THESUGUNA"
    - label: "Privacy policy"
      icon: "fas fa-shield-alt"
      #icon: "fab fa-fw fa-shield"
      url: "/privacy-policy/"

